# Generated by Django 5.1.2 on 2024-11-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('preco', models.DecimalField(db_column='preco', decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(db_column='descricao', default='Acesso total à academia por um mês')),
                ('duracao', models.IntegerField(db_column='duracao', default=1)),
                ('tipo_acesso', models.CharField(db_column='tipo_Acesso', default='total', max_length=50)),
                ('academia', models.ForeignKey(db_column='academia', on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='academia.academia')),
            ],
            options={
                'db_table': 'plano',
            },
        ),
    ]
