# Generated by Django 5.1.2 on 2024-10-15 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plano',
            old_name='academia',
            new_name='id_academia',
        ),
    ]
