# Generated by Django 5.1.2 on 2024-11-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='tipo_acesso',
        ),
    ]
