# Generated by Django 5.1.2 on 2025-03-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0002_remove_plano_tipo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='desconto_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='descricao_beneficio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='dias_permitidos',
            field=models.JSONField(db_column='dias_permitidos', default=list, help_text='Lista de dias da semana em que o plano pode ser usado'),
        ),
        migrations.AddField(
            model_name='plano',
            name='tipo_beneficio',
            field=models.CharField(choices=[('desconto', 'Desconto em produtos'), ('outros', 'Outros'), ('nenhum', 'Nenhum')], default='nenhum', max_length=100),
        ),
    ]
