# Generated by Django 5.1.2 on 2025-03-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0003_plano_desconto_percentual_plano_descricao_beneficio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='dias_permitidos',
            field=models.JSONField(db_column='dias_permitidos', default=['segunda', 'terca', 'quarta', 'quinta', 'sexta', 'sabado', 'domingo'], help_text='Lista de dias da semana em que o plano pode ser usado'),
        ),
    ]
