# Generated by Django 5.1.2 on 2025-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0004_alter_plano_dias_permitidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('tipo_beneficio', models.CharField(choices=[('desconto', 'Desconto em produtos'), ('outros', 'Outros'), ('nenhum', 'Nenhum')], default='nenhum')),
                ('descricao', models.CharField(blank=True, help_text='Descricao detalhada dobeneficio', null=True)),
                ('desconto_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de desconto', max_digits=5, null=True)),
            ],
            options={
                'db_table': 'beneficio',
            },
        ),
        migrations.RemoveField(
            model_name='plano',
            name='desconto_percentual',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='descricao_beneficio',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='tipo_beneficio',
        ),
        migrations.AddField(
            model_name='plano',
            name='beneficios',
            field=models.ManyToManyField(blank=True, related_name='planos', to='plano.beneficio'),
        ),
    ]
