# Generated by Django 5.1.2 on 2025-03-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0006_alter_plano_dias_permitidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='beneficios',
        ),
        migrations.AddField(
            model_name='plano',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Beneficio',
        ),
        migrations.AddField(
            model_name='plano',
            name='beneficios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
