# Generated by Django 5.1.2 on 2025-03-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0007_remove_plano_beneficios_plano_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='beneficios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
