# Generated by Django 5.1.2 on 2025-03-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0008_alter_plano_beneficios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='beneficios',
        ),
    ]
