# Generated by Django 5.1.2 on 2025-03-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0009_remove_plano_beneficios'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='beneficios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
