# Generated by Django 5.1.2 on 2025-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0010_plano_beneficios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='beneficios',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
