# Generated by Django 5.1.2 on 2025-05-04 13:40

import plano.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0011_alter_plano_beneficios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='dias_permitidos',
            field=models.JSONField(db_column='dias_permitidos', default=plano.models.dias_semana_default, help_text='Lista de dias da semana em que o plano pode ser usado'),
        ),
    ]
