# Generated by Django 5.1.2 on 2025-05-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0012_alter_plano_dias_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='total_alunos',
            field=models.PositiveIntegerField(db_column='total_alunos', default=0),
        ),
    ]
