# Generated by Django 5.1.2 on 2025-05-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('data_pagamento', models.DateField(auto_now_add=True, db_column='data_pagamento')),
                ('data_vencimento', models.DateField(db_column='data_vencimento')),
                ('tipo_pagamento', models.CharField(choices=[('C', 'Cartao'), ('D', 'Dinheiro'), ('P', 'Pix')], db_column='tipo_pagamento', default='D', max_length=1)),
                ('valor', models.FloatField(db_column='valor', default=0)),
                ('aluno_plano', models.ForeignKey(db_column='aluno_plano', on_delete=django.db.models.deletion.CASCADE, to='aluno.alunoplano')),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
    ]
