# Generated by Django 5.1.2 on 2024-11-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(choices=[('C', 'Cartao'), ('D', 'Dinheiro'), ('P', 'Pix')], db_column='tipo_pagamento', default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.FloatField(db_column='valor', default=0),
        ),
    ]
