services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=my_gym
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=my_gym
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: