services:
  postgres:
    image: postgres
    container_name: postgres_new
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=my_gym
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=my_gym
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: >
      postgres -c listen_addresses='*'

  minio:
    image: minio/minio
    container_name: minio_mygym_new
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]


  gym_face_service:
    build: ./facial_gym
    container_name: gym_face_service
    ports:
      - "8001:8001"
    env_file:
      - ./facial_gym/.env
    volumes:
      - ./facial_gym:/app


  backend:
    image: ryankazz/mygym-backend:1.0
    build: ./my_gym
    container_name: mygym-backend
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DEBUG=1
      - DB_NAME=my_gym
      - DB_USER=my_gym
      - DB_PASSWORD=123
      - DB_HOST=postgres
      - DB_PORT=5432

  frontend:
    image: ryankazz/mygym-frontend:1.0
    build: ./my-gym-frontend
    container_name: mygym-frontend
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  postgres-data:
  minio-data:
  redis_data:

