services:
  postgres:
    image: postgres
    container_name: postgres_new
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=my_gym
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=my_gym
    volumes:
        - postgres-data:/var/lib/postgresql/data
    command: >
      postgres -c listen_addresses='*'

  minio:
    image: minio/minio
    container_name: minio_mygym_new
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]


  backend:
      build: ./my_gym

      command: >
        sh -c "python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
#      volumes:
#        - ./backend:/app
      ports:
        - "8000:8000"
      depends_on:
        - postgres
      environment:
        - DEBUG=1
        - DB_NAME=my_gym
        - DB_USER=my_gym
        - DB_PASSWORD=123
        - DB_HOST=postgres
        - DB_PORT=5432

#  nginx:
#    image: nginx:alpine
#    container_name: my-gym-nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./my-gym-frontend/dist/my-gym-frontend/browser:/usr/share/nginx/html
#      - ./my-gym-frontend/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./my-gym-frontend/mime.types:/etc/nginx/mime.types:ro
#    depends_on:
#      - postgres

volumes:
  postgres-data:
  minio-data:
  redis_data:

