--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4 (Debian 17.4-1.pgdg120+2)
-- Dumped by pg_dump version 17.4 (Debian 17.4-1.pgdg120+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academia; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.academia (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    name character varying(100) NOT NULL,
    endereco character varying(200) NOT NULL,
    telefone character varying(100),
    email character varying(254)
);


ALTER TABLE public.academia OWNER TO my_gym;

--
-- Name: academia_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.academia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aluno; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.aluno (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    nome character varying(100) NOT NULL,
    telefone character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    data_nascimento date NOT NULL,
    matricula character varying(20) NOT NULL,
    user_id integer
);


ALTER TABLE public.aluno OWNER TO my_gym;

--
-- Name: aluno_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.aluno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aluno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aluno_plano; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.aluno_plano (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    data_vencimento date,
    aluno bigint NOT NULL,
    plano bigint NOT NULL
);


ALTER TABLE public.aluno_plano OWNER TO my_gym;

--
-- Name: aluno_plano_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.aluno_plano ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.aluno_plano_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO my_gym;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO my_gym;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO my_gym;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO my_gym;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO my_gym;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO my_gym;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO my_gym;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO my_gym;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO my_gym;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO my_gym;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO my_gym;

--
-- Name: frequencia; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.frequencia (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    data timestamp with time zone NOT NULL,
    academia bigint NOT NULL,
    aluno bigint NOT NULL
);


ALTER TABLE public.frequencia OWNER TO my_gym;

--
-- Name: frequencia_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.frequencia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.frequencia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_venda; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.item_venda (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    quantidade integer NOT NULL,
    preco_unitario numeric(10,2) NOT NULL,
    produto_id bigint,
    venda_id bigint,
    CONSTRAINT item_venda_quantidade_check CHECK ((quantidade >= 0))
);


ALTER TABLE public.item_venda OWNER TO my_gym;

--
-- Name: item_venda_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.item_venda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_venda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lote_produto; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.lote_produto (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    quantidade integer NOT NULL,
    data_validade date NOT NULL,
    data_entrada timestamp with time zone NOT NULL,
    preco_total numeric(10,2) NOT NULL,
    preco_unitario numeric(10,2) NOT NULL,
    produto_id bigint NOT NULL,
    CONSTRAINT lote_produto_quantidade_check CHECK ((quantidade >= 0))
);


ALTER TABLE public.lote_produto OWNER TO my_gym;

--
-- Name: lote_produto_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.lote_produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lote_produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagamento; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.pagamento (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    data_pagamento date NOT NULL,
    data_vencimento date NOT NULL,
    tipo_pagamento character varying(1) NOT NULL,
    valor double precision NOT NULL,
    aluno_plano bigint NOT NULL
);


ALTER TABLE public.pagamento OWNER TO my_gym;

--
-- Name: pagamento_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.pagamento ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagamento_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plano; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.plano (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    nome character varying(100) NOT NULL,
    preco numeric(10,2) NOT NULL,
    descricao text NOT NULL,
    duracao integer NOT NULL,
    beneficios jsonb NOT NULL,
    desconto numeric(5,2),
    dias_permitidos jsonb NOT NULL,
    total_alunos integer NOT NULL,
    academia bigint NOT NULL,
    CONSTRAINT plano_total_alunos_check CHECK ((total_alunos >= 0))
);


ALTER TABLE public.plano OWNER TO my_gym;

--
-- Name: plano_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.plano ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plano_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produto; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.produto (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    marca character varying(200),
    nome character varying(100) NOT NULL,
    descricao text NOT NULL,
    preco numeric(10,2) NOT NULL,
    foto character varying(200),
    data_cadastro date NOT NULL,
    quantidade_estoque integer NOT NULL,
    estoque_minimo integer NOT NULL,
    categoria character varying(100) NOT NULL,
    academia_id bigint NOT NULL,
    CONSTRAINT produto_estoque_minimo_check CHECK ((estoque_minimo >= 0)),
    CONSTRAINT produto_quantidade_estoque_check CHECK ((quantidade_estoque >= 0))
);


ALTER TABLE public.produto OWNER TO my_gym;

--
-- Name: produto_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.produto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    question text NOT NULL,
    answer text,
    aluno_id bigint,
    usuario_id integer
);


ALTER TABLE public.questions OWNER TO my_gym;

--
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.usuario (
    user_ptr_id integer NOT NULL,
    nome character varying(100) NOT NULL,
    tipo_usuario character varying(1) NOT NULL
);


ALTER TABLE public.usuario OWNER TO my_gym;

--
-- Name: usuario_academia; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.usuario_academia (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    tipo_usuario character varying(1) NOT NULL,
    data_contratacao timestamp with time zone NOT NULL,
    academia bigint NOT NULL,
    usuario integer NOT NULL
);


ALTER TABLE public.usuario_academia OWNER TO my_gym;

--
-- Name: usuario_academia_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.usuario_academia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_academia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: venda; Type: TABLE; Schema: public; Owner: my_gym
--

CREATE TABLE public.venda (
    id bigint NOT NULL,
    dt_created timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active boolean NOT NULL,
    data_venda timestamp with time zone NOT NULL,
    valor_total numeric(10,2) NOT NULL,
    academia_id bigint,
    cliente_id bigint,
    vendedor_id integer
);


ALTER TABLE public.venda OWNER TO my_gym;

--
-- Name: venda_id_seq; Type: SEQUENCE; Schema: public; Owner: my_gym
--

ALTER TABLE public.venda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: academia academia_email_key; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.academia
    ADD CONSTRAINT academia_email_key UNIQUE (email);


--
-- Name: academia academia_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.academia
    ADD CONSTRAINT academia_pkey PRIMARY KEY (id);


--
-- Name: aluno aluno_email_key; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_email_key UNIQUE (email);


--
-- Name: aluno aluno_matricula_key; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_matricula_key UNIQUE (matricula);


--
-- Name: aluno aluno_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_pkey PRIMARY KEY (id);


--
-- Name: aluno_plano aluno_plano_aluno_plano_6ee7d48c_uniq; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno_plano
    ADD CONSTRAINT aluno_plano_aluno_plano_6ee7d48c_uniq UNIQUE (aluno, plano);


--
-- Name: aluno_plano aluno_plano_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno_plano
    ADD CONSTRAINT aluno_plano_pkey PRIMARY KEY (id);


--
-- Name: aluno aluno_user_id_key; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_user_id_key UNIQUE (user_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: frequencia frequencia_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.frequencia
    ADD CONSTRAINT frequencia_pkey PRIMARY KEY (id);


--
-- Name: item_venda item_venda_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.item_venda
    ADD CONSTRAINT item_venda_pkey PRIMARY KEY (id);


--
-- Name: lote_produto lote_produto_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.lote_produto
    ADD CONSTRAINT lote_produto_pkey PRIMARY KEY (id);


--
-- Name: pagamento pagamento_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.pagamento
    ADD CONSTRAINT pagamento_pkey PRIMARY KEY (id);


--
-- Name: plano plano_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.plano
    ADD CONSTRAINT plano_pkey PRIMARY KEY (id);


--
-- Name: produto produto_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_pkey PRIMARY KEY (id);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: usuario_academia usuario_academia_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.usuario_academia
    ADD CONSTRAINT usuario_academia_pkey PRIMARY KEY (id);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (user_ptr_id);


--
-- Name: venda venda_pkey; Type: CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT venda_pkey PRIMARY KEY (id);


--
-- Name: academia_email_51d11351_like; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX academia_email_51d11351_like ON public.academia USING btree (email varchar_pattern_ops);


--
-- Name: aluno_email_41f87c09_like; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX aluno_email_41f87c09_like ON public.aluno USING btree (email varchar_pattern_ops);


--
-- Name: aluno_matricula_193255eb_like; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX aluno_matricula_193255eb_like ON public.aluno USING btree (matricula varchar_pattern_ops);


--
-- Name: aluno_plano_aluno_4f3baff1; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX aluno_plano_aluno_4f3baff1 ON public.aluno_plano USING btree (aluno);


--
-- Name: aluno_plano_plano_33dcb5c3; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX aluno_plano_plano_33dcb5c3 ON public.aluno_plano USING btree (plano);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: frequencia_academia_6b6c7904; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX frequencia_academia_6b6c7904 ON public.frequencia USING btree (academia);


--
-- Name: frequencia_aluno_0cbda87a; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX frequencia_aluno_0cbda87a ON public.frequencia USING btree (aluno);


--
-- Name: item_venda_produto_id_9e632808; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX item_venda_produto_id_9e632808 ON public.item_venda USING btree (produto_id);


--
-- Name: item_venda_venda_id_8a275b51; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX item_venda_venda_id_8a275b51 ON public.item_venda USING btree (venda_id);


--
-- Name: lote_produto_produto_id_3a5fd19e; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX lote_produto_produto_id_3a5fd19e ON public.lote_produto USING btree (produto_id);


--
-- Name: pagamento_aluno_plano_63b46a4c; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX pagamento_aluno_plano_63b46a4c ON public.pagamento USING btree (aluno_plano);


--
-- Name: plano_academia_6017a89e; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX plano_academia_6017a89e ON public.plano USING btree (academia);


--
-- Name: produto_academia_id_0f3b9ed4; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX produto_academia_id_0f3b9ed4 ON public.produto USING btree (academia_id);


--
-- Name: questions_aluno_id_981b9cac; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX questions_aluno_id_981b9cac ON public.questions USING btree (aluno_id);


--
-- Name: questions_usuario_id_85867c0c; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX questions_usuario_id_85867c0c ON public.questions USING btree (usuario_id);


--
-- Name: usuario_academia_academia_2b28677c; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX usuario_academia_academia_2b28677c ON public.usuario_academia USING btree (academia);


--
-- Name: usuario_academia_usuario_eb9ee674; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX usuario_academia_usuario_eb9ee674 ON public.usuario_academia USING btree (usuario);


--
-- Name: venda_academia_id_064a5307; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX venda_academia_id_064a5307 ON public.venda USING btree (academia_id);


--
-- Name: venda_cliente_id_e23435ae; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX venda_cliente_id_e23435ae ON public.venda USING btree (cliente_id);


--
-- Name: venda_vendedor_id_3bd3ddd6; Type: INDEX; Schema: public; Owner: my_gym
--

CREATE INDEX venda_vendedor_id_3bd3ddd6 ON public.venda USING btree (vendedor_id);


--
-- Name: aluno_plano aluno_plano_aluno_4f3baff1_fk_aluno_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno_plano
    ADD CONSTRAINT aluno_plano_aluno_4f3baff1_fk_aluno_id FOREIGN KEY (aluno) REFERENCES public.aluno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aluno_plano aluno_plano_plano_33dcb5c3_fk_plano_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno_plano
    ADD CONSTRAINT aluno_plano_plano_33dcb5c3_fk_plano_id FOREIGN KEY (plano) REFERENCES public.plano(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: aluno aluno_user_id_0036d271_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.aluno
    ADD CONSTRAINT aluno_user_id_0036d271_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: frequencia frequencia_academia_6b6c7904_fk_academia_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.frequencia
    ADD CONSTRAINT frequencia_academia_6b6c7904_fk_academia_id FOREIGN KEY (academia) REFERENCES public.academia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: frequencia frequencia_aluno_0cbda87a_fk_aluno_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.frequencia
    ADD CONSTRAINT frequencia_aluno_0cbda87a_fk_aluno_id FOREIGN KEY (aluno) REFERENCES public.aluno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: item_venda item_venda_produto_id_9e632808_fk_produto_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.item_venda
    ADD CONSTRAINT item_venda_produto_id_9e632808_fk_produto_id FOREIGN KEY (produto_id) REFERENCES public.produto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: item_venda item_venda_venda_id_8a275b51_fk_venda_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.item_venda
    ADD CONSTRAINT item_venda_venda_id_8a275b51_fk_venda_id FOREIGN KEY (venda_id) REFERENCES public.venda(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lote_produto lote_produto_produto_id_3a5fd19e_fk_produto_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.lote_produto
    ADD CONSTRAINT lote_produto_produto_id_3a5fd19e_fk_produto_id FOREIGN KEY (produto_id) REFERENCES public.produto(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pagamento pagamento_aluno_plano_63b46a4c_fk_aluno_plano_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.pagamento
    ADD CONSTRAINT pagamento_aluno_plano_63b46a4c_fk_aluno_plano_id FOREIGN KEY (aluno_plano) REFERENCES public.aluno_plano(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: plano plano_academia_6017a89e_fk_academia_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.plano
    ADD CONSTRAINT plano_academia_6017a89e_fk_academia_id FOREIGN KEY (academia) REFERENCES public.academia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: produto produto_academia_id_0f3b9ed4_fk_academia_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT produto_academia_id_0f3b9ed4_fk_academia_id FOREIGN KEY (academia_id) REFERENCES public.academia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions questions_aluno_id_981b9cac_fk_aluno_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_aluno_id_981b9cac_fk_aluno_id FOREIGN KEY (aluno_id) REFERENCES public.aluno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions questions_usuario_id_85867c0c_fk_usuario_user_ptr_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_usuario_id_85867c0c_fk_usuario_user_ptr_id FOREIGN KEY (usuario_id) REFERENCES public.usuario(user_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuario_academia usuario_academia_academia_2b28677c_fk_academia_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.usuario_academia
    ADD CONSTRAINT usuario_academia_academia_2b28677c_fk_academia_id FOREIGN KEY (academia) REFERENCES public.academia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuario_academia usuario_academia_usuario_eb9ee674_fk_usuario_user_ptr_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.usuario_academia
    ADD CONSTRAINT usuario_academia_usuario_eb9ee674_fk_usuario_user_ptr_id FOREIGN KEY (usuario) REFERENCES public.usuario(user_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuario usuario_user_ptr_id_1f99d425_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_user_ptr_id_1f99d425_fk_auth_user_id FOREIGN KEY (user_ptr_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: venda venda_academia_id_064a5307_fk_academia_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT venda_academia_id_064a5307_fk_academia_id FOREIGN KEY (academia_id) REFERENCES public.academia(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: venda venda_cliente_id_e23435ae_fk_aluno_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT venda_cliente_id_e23435ae_fk_aluno_id FOREIGN KEY (cliente_id) REFERENCES public.aluno(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: venda venda_vendedor_id_3bd3ddd6_fk_usuario_user_ptr_id; Type: FK CONSTRAINT; Schema: public; Owner: my_gym
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT venda_vendedor_id_3bd3ddd6_fk_usuario_user_ptr_id FOREIGN KEY (vendedor_id) REFERENCES public.usuario(user_ptr_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

