# Generated by Django 5.1.2 on 2024-11-05 01:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('telefone', models.CharField(db_column='telefone', max_length=100, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('data_nascimento', models.DateField(db_column='data_nascimento', default=datetime.datetime.now)),
                ('matricula', models.CharField(blank=True, db_column='matricula', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')])),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='AlunoAcademia',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('academia', models.ForeignKey(db_column='id_academia', on_delete=django.db.models.deletion.CASCADE, related_name='alunos_academia', to='academia.academia')),
                ('aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, related_name='alunos_academia', to='aluno.aluno')),
            ],
            options={
                'db_table': 'aluno_academia',
            },
        ),
        migrations.CreateModel(
            name='AlunoPlano',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('aluno', models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, related_name='alunos_plano', to='aluno.aluno')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_plano', to='plano.plano')),
            ],
            options={
                'db_table': 'aluno_plano',
            },
        ),
    ]
