# Generated by Django 5.1.2 on 2024-10-13 22:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0002_frequencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('telefone', models.CharField(db_column='telefone', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Insira um número de telefone válido.', regex='^\\+?[0-9]*$')])),
                ('email', models.EmailField(db_column='e-mail', max_length=254, null=True, validators=[django.core.validators.EmailValidator(message='Insira um e-mail válido.')])),
                ('id_academia', models.ForeignKey(db_column='id_academia', on_delete=django.db.models.deletion.CASCADE, to='academia.academia')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
