# Generated by Django 5.1.2 on 2025-05-27 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('plano', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alunoplano',
            name='aluno',
            field=models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.CASCADE, related_name='alunos_plano', to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='alunoplano',
            name='plano',
            field=models.ForeignKey(db_column='plano', on_delete=django.db.models.deletion.CASCADE, related_name='alunos_plano', to='plano.plano'),
        ),
        migrations.AlterUniqueTogether(
            name='alunoplano',
            unique_together={('aluno', 'plano')},
        ),
    ]
