# Generated by Django 5.1.2 on 2024-11-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunoAcademia',
        ),
    ]
