# Generated by Django 5.1.2 on 2025-06-17 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0002_initial'),
        ('aluno', '0001_initial'),
        ('plano', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alunoplano',
            name='aluno',
            field=models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.CASCADE, related_name='alunos_plano', to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='alunoplano',
            name='plano',
            field=models.ForeignKey(db_column='plano', on_delete=django.db.models.deletion.CASCADE, related_name='alunos_plano', to='plano.plano'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academia.exercise'),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='workout_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='aluno.workoutday'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='member_plan',
            field=models.ForeignKey(db_column='member_plan', on_delete=django.db.models.deletion.CASCADE, related_name='work_out_plans', to='aluno.alunoplano'),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='workout_plan',
            field=models.ForeignKey(db_column='workout_plan', on_delete=django.db.models.deletion.CASCADE, related_name='workout_days', to='aluno.workoutplan'),
        ),
        migrations.AlterUniqueTogether(
            name='alunoplano',
            unique_together={('aluno', 'plano')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('workout_plan', 'days_of_week')},
        ),
    ]
