# Generated by Django 5.1.2 on 2024-10-13 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='id_plano',
            field=models.ForeignKey(db_column='id_plano', on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='plano.plano'),
        ),
    ]
