# Generated by Django 5.1.2 on 2024-11-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_delete_alunoacademia'),
        ('plano', '0002_remove_plano_tipo_acesso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alunoplano',
            unique_together={('aluno', 'plano')},
        ),
    ]
