# Generated by Django 5.1.2 on 2025-05-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_alunoplano_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoplano',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
