# Generated by Django 5.1.2 on 2024-11-07 15:44

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(db_column='nome', max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('D', 'Dono'), ('G', 'Gerente'), ('A', 'Atendente')], db_column='tipo_usuario', default='D', max_length=1)),
            ],
            options={
                'db_table': 'usuario',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
