# Generated by Django 5.1.2 on 2024-10-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('D', 'Dono'), ('G', 'Gerente'), ('F', 'Funcionário')], db_column='tipo_usuario', default='D', max_length=1),
        ),
    ]
