# Generated by Django 5.1.2 on 2024-11-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('D', 'Dono'), ('G', 'Gerente'), ('A', 'Atendente')], db_column='tipo_usuario', max_length=1),
        ),
    ]
