# Generated by Django 5.1.2 on 2025-05-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0005_usuarioacademia_data_contratacao'),
        ('aluno', '0003_alter_alunoplano_unique_together'),
        ('produto', '0003_produto_marca_alter_produto_foto'),
        ('usuario', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academia.academia')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='aluno.aluno')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
                ('venda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='venda.venda')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
