# Generated by Django 5.1.2 on 2025-06-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('venda', '0002_itemvenda_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.loteproduto'),
        ),
    ]
