# Generated by Django 5.1.2 on 2025-05-24 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_alter_itemvenda_options_alter_venda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvenda',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='itemvenda',
            table=None,
        ),
        migrations.AlterModelTable(
            name='venda',
            table=None,
        ),
    ]
