# Generated by Django 5.1.2 on 2025-06-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_itemvenda_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='lote',
        ),
    ]
