# Generated by Django 5.1.2 on 2025-05-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0004_alter_itemvenda_options_alter_venda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemvenda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={},
        ),
        migrations.AlterModelTable(
            name='itemvenda',
            table='item_venda',
        ),
        migrations.AlterModelTable(
            name='venda',
            table='venda',
        ),
    ]
