# Generated by Django 5.1.2 on 2025-06-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_delete_historicalproduto'),
        ('venda', '0004_remove_itemvenda_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.loteproduto'),
        ),
    ]
