# Generated by Django 5.2.1 on 2025-06-07 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_remove_student_face_image_alter_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face_encoding',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encodings', to='checkin.student')),
            ],
        ),
    ]
