# Generated by Django 5.1.2 on 2025-06-17 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('nome', models.CharField(db_column='name', max_length=100)),
                ('endereco', models.CharField(db_column='endereco', max_length=200)),
                ('telefone', models.CharField(db_column='telefone', max_length=100, null=True)),
                ('email', models.EmailField(db_column='email', max_length=254, null=True, unique=True)),
            ],
            options={
                'db_table': 'academia',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('data', models.DateTimeField(auto_now_add=True, db_column='data')),
            ],
            options={
                'db_table': 'frequencia',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('tipo', models.CharField(choices=[('energia', 'Energia Elétrica'), ('agua', 'Água'), ('salario', 'Salário de Funcionários'), ('manutencao', 'Manutenção'), ('produtos', 'Reabastecimento de Produtos'), ('limpeza', 'Materiais de Limpeza'), ('impostos', 'Impostos e Taxas'), ('outros', 'Outros')], db_column='tipo', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(blank=True, db_column='data', null=True)),
            ],
            options={
                'db_table': 'gasto',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAcademia',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('tipo_usuario', models.CharField(choices=[('D', 'Dono'), ('G', 'Gerente'), ('A', 'Atendente'), ('M', 'Membro')], db_column='tipo_usuario', max_length=1)),
                ('data_contratacao', models.DateTimeField(auto_now_add=True, db_column='data_contratacao')),
            ],
            options={
                'db_table': 'usuario_academia',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('muscle_group', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exercises', to='academia.academia')),
            ],
            options={
                'db_table': 'exercise',
            },
        ),
    ]
