# Generated by Django 5.1.2 on 2025-05-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='usuarioacademia',
            name='academia',
            field=models.ForeignKey(db_column='academia', on_delete=django.db.models.deletion.CASCADE, to='academia.academia'),
        ),
    ]
