# Generated by Django 5.1.2 on 2024-11-05 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        ('aluno', '0001_initial'),
        ('usuario', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='usuarioacademia',
            name='academia',
            field=models.ForeignKey(db_column='id_academia', on_delete=django.db.models.deletion.CASCADE, to='academia.academia'),
        ),
        migrations.AddField(
            model_name='usuarioacademia',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
