# Generated by Django 5.1.2 on 2025-06-17 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        ('aluno', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='register_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='academia',
            field=models.ForeignKey(db_column='academia', on_delete=django.db.models.deletion.CASCADE, to='academia.academia'),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='aluno',
            field=models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='academia',
            field=models.ForeignKey(db_column='academia', on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='academia.academia'),
        ),
        migrations.AddField(
            model_name='usuarioacademia',
            name='academia',
            field=models.ForeignKey(db_column='academia', on_delete=django.db.models.deletion.CASCADE, to='academia.academia'),
        ),
        migrations.AddField(
            model_name='usuarioacademia',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
