# Generated by Django 5.1.2 on 2024-10-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_frequencia'),
        ('aluno', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='id_aluno',
            field=models.ForeignKey(db_column='id_aluno', on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
        ),
    ]
