# Generated by Django 5.1.2 on 2024-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioacademia',
            name='tipo_usuario',
            field=models.CharField(choices=[('D', 'Dono'), ('G', 'Gerente'), ('A', 'Atendente')], db_column='tipo_usuario', default='D', max_length=1),
        ),
    ]
