# Generated by Django 5.1.2 on 2025-06-01 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('tipo', models.CharField(choices=[('energia', 'Energia Elétrica'), ('agua', 'Água'), ('salario', 'Salário de Funcionários'), ('manutencao', 'Manutenção'), ('produtos', 'Reabastecimento de Produtos'), ('limpeza', 'Materiais de Limpeza'), ('impostos', 'Impostos e Taxas'), ('outros', 'Outros')], db_column='tipo', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(blank=True, db_column='data', null=True)),
                ('academia', models.ForeignKey(db_column='academia', on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='academia.academia')),
            ],
            options={
                'db_table': 'gasto',
            },
        ),
    ]
