# Generated by Django 5.1.2 on 2024-10-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_alter_frequencia_id_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='data',
            field=models.DateTimeField(auto_now_add=True, db_column='data'),
        ),
    ]
