# Generated by Django 5.1.2 on 2024-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='email',
            field=models.EmailField(db_column='email', max_length=254, null=True, unique=True),
        ),
    ]
