# Generated by Django 5.1.2 on 2024-10-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_frequencia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia',
            name='data',
            field=models.DateField(auto_now_add=True, db_column='data'),
        ),
    ]
