# Generated by Django 5.1.2 on 2025-04-02 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_academia_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioacademia',
            name='data_contratacao',
            field=models.DateTimeField(auto_now_add=True, db_column='data_contratacao', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
