# Generated by Django 5.1.2 on 2025-06-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercice',
            name='academia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='exercices', to='academia.academia'),
        ),
    ]
