# This is a reference file containing the SQL schema for the database
# It is not meant to be loaded during startup
# The original class has been modified to prevent it from being initialized during import

class SQLBaseContext:
    def __init__(self, db):
        self.db = db

        db = """
            
            create table academia
(
    id          bigint generated by default as identity
        primary key,
    dt_created  timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active   boolean      not null,
    name        varchar(100) not null,
    endereco    varchar(200) not null,
    telefone    varchar(100),
    email       varchar(254)
        constraint academia_email_51d11351_uniq
            unique
);

alter table academia
    owner to my_gym;

create index academia_email_51d11351_like
    on academia (email varchar_pattern_ops);

create table aluno
(
    id              bigint generated by default as identity
        primary key,
    dt_created      timestamp with time zone,
    dt_modified     timestamp with time zone,
    cs_active       boolean      not null,
    nome            varchar(100) not null,
    telefone        varchar(100) not null,
    email           varchar(254) not null
        unique,
    data_nascimento date         not null,
    matricula       varchar(20)  not null
        unique
);

alter table aluno
    owner to my_gym;

create index aluno_email_41f87c09_like
    on aluno (email varchar_pattern_ops);

create index aluno_matricula_193255eb_like
    on aluno (matricula varchar_pattern_ops);

create table auth_group
(
    id   integer generated by default as identity
        primary key,
    name varchar(150) not null
        unique
);

alter table auth_group
    owner to my_gym;

create index auth_group_name_a6ea08ec_like
    on auth_group (name varchar_pattern_ops);

create table auth_user
(
    id           integer generated by default as identity
        primary key,
    password     varchar(128)             not null,
    last_login   timestamp with time zone,
    is_superuser boolean                  not null,
    username     varchar(150)             not null
        unique,
    first_name   varchar(150)             not null,
    last_name    varchar(150)             not null,
    email        varchar(254)             not null,
    is_staff     boolean                  not null,
    is_active    boolean                  not null,
    date_joined  timestamp with time zone not null
);

alter table auth_user
    owner to my_gym;

create index auth_user_username_6821ab7c_like
    on auth_user (username varchar_pattern_ops);

create table auth_user_groups
(
    id       bigint generated by default as identity
        primary key,
    user_id  integer not null
        constraint auth_user_groups_user_id_6a12ed8b_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    group_id integer not null
        constraint auth_user_groups_group_id_97559544_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    constraint auth_user_groups_user_id_group_id_94350c0c_uniq
        unique (user_id, group_id)
);

alter table auth_user_groups
    owner to my_gym;

create index auth_user_groups_group_id_97559544
    on auth_user_groups (group_id);

create index auth_user_groups_user_id_6a12ed8b
    on auth_user_groups (user_id);

create table authtoken_token
(
    key     varchar(40)              not null
        primary key,
    created timestamp with time zone not null,
    user_id integer                  not null
        unique
        constraint authtoken_token_user_id_35299eff_fk_auth_user_id
            references auth_user
            deferrable initially deferred
);

alter table authtoken_token
    owner to my_gym;

create index authtoken_token_key_10f0b77e_like
    on authtoken_token (key varchar_pattern_ops);

create table django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table django_content_type
    owner to my_gym;

create table auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table auth_permission
    owner to my_gym;

create table auth_group_permissions
(
    id            bigint generated by default as identity
        primary key,
    group_id      integer not null
        constraint auth_group_permissions_group_id_b120cbf9_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_group_permissio_permission_id_84c5c92e_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_group_permissions_group_id_permission_id_0cd325b0_uniq
        unique (group_id, permission_id)
);

alter table auth_group_permissions
    owner to my_gym;

create index auth_group_permissions_group_id_b120cbf9
    on auth_group_permissions (group_id);

create index auth_group_permissions_permission_id_84c5c92e
    on auth_group_permissions (permission_id);

create index auth_permission_content_type_id_2f476e4b
    on auth_permission (content_type_id);

create table auth_user_user_permissions
(
    id            bigint generated by default as identity
        primary key,
    user_id       integer not null
        constraint auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    permission_id integer not null
        constraint auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint auth_user_user_permissions_user_id_permission_id_14a6b632_uniq
        unique (user_id, permission_id)
);

alter table auth_user_user_permissions
    owner to my_gym;

create index auth_user_user_permissions_permission_id_1fbb5f2c
    on auth_user_user_permissions (permission_id);

create index auth_user_user_permissions_user_id_a95ead1b
    on auth_user_user_permissions (user_id);

create table django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references django_content_type
            deferrable initially deferred,
    user_id         integer                  not null
        constraint django_admin_log_user_id_c564eba6_fk_auth_user_id
            references auth_user
            deferrable initially deferred
);

alter table django_admin_log
    owner to my_gym;

create index django_admin_log_content_type_id_c4bce8eb
    on django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on django_admin_log (user_id);

create table django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table django_migrations
    owner to my_gym;

create table django_session
(
    session_key  varchar(40)              not null
        primary key,
    session_data text                     not null,
    expire_date  timestamp with time zone not null
);

alter table django_session
    owner to my_gym;

create index django_session_expire_date_a5c62663
    on django_session (expire_date);

create index django_session_session_key_c0390e0f_like
    on django_session (session_key varchar_pattern_ops);

create table frequencia
(
    id          bigint generated by default as identity
        primary key,
    dt_created  timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active   boolean                  not null,
    data        timestamp with time zone not null,
    academia    bigint                   not null
        constraint frequencia_academia_6b6c7904_fk_academia_id
            references academia
            deferrable initially deferred,
    aluno       bigint                   not null
        constraint frequencia_aluno_0cbda87a_fk_aluno_id
            references aluno
            deferrable initially deferred
);

alter table frequencia
    owner to my_gym;

create index frequencia_academia_6b6c7904
    on frequencia (academia);

create index frequencia_aluno_0cbda87a
    on frequencia (aluno);

create table plano
(
    id              bigint generated by default as identity
        primary key,
    dt_created      timestamp with time zone,
    dt_modified     timestamp with time zone,
    cs_active       boolean        not null,
    nome            varchar(100)   not null,
    preco           numeric(10, 2) not null,
    descricao       text           not null,
    duracao         integer        not null,
    academia        bigint         not null
        constraint plano_academia_6017a89e_fk_academia_id
            references academia
            deferrable initially deferred,
    dias_permitidos jsonb          not null,
    desconto        numeric(5, 2)
);

alter table plano
    owner to my_gym;

create table aluno_plano
(
    id          bigint generated by default as identity
        primary key,
    dt_created  timestamp with time zone,
    dt_modified timestamp with time zone,
    cs_active   boolean not null,
    aluno       bigint  not null
        constraint aluno_plano_aluno_4f3baff1_fk_aluno_id
            references aluno
            deferrable initially deferred,
    plano       bigint  not null
        constraint aluno_plano_plano_33dcb5c3_fk_plano_id
            references plano
            deferrable initially deferred,
    constraint aluno_plano_aluno_plano_6ee7d48c_uniq
        unique (aluno, plano)
);

alter table aluno_plano
    owner to my_gym;

create index aluno_plano_aluno_4f3baff1
    on aluno_plano (aluno);

create index aluno_plano_plano_33dcb5c3
    on aluno_plano (plano);

create table pagamento
(
    id              bigint generated by default as identity
        primary key,
    dt_created      timestamp with time zone,
    dt_modified     timestamp with time zone,
    cs_active       boolean          not null,
    data_pagamento  date             not null,
    data_vencimento date             not null,
    aluno_plano     bigint           not null
        constraint pagamento_aluno_plano_63b46a4c_fk_aluno_plano_id
            references aluno_plano
            deferrable initially deferred,
    tipo_pagamento  varchar(1)       not null,
    valor           double precision not null
);

alter table pagamento
    owner to my_gym;

create index pagamento_aluno_plano_63b46a4c
    on pagamento (aluno_plano);

create index plano_academia_6017a89e
    on plano (academia);

create table usuario
(
    user_ptr_id  integer      not null
        primary key
        constraint usuario_user_ptr_id_1f99d425_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    nome         varchar(100) not null,
    tipo_usuario varchar(1)   not null
);

alter table usuario
    owner to my_gym;

create table usuario_academia
(
    id           bigint generated by default as identity
        primary key,
    dt_created   timestamp with time zone,
    dt_modified  timestamp with time zone,
    cs_active    boolean    not null,
    tipo_usuario varchar(1) not null,
    academia     bigint     not null
        constraint usuario_academia_academia_2b28677c_fk_academia_id
            references academia
            deferrable initially deferred,
    usuario      integer    not null
        constraint usuario_academia_usuario_eb9ee674_fk_usuario_user_ptr_id
            references usuario
            deferrable initially deferred
);

alter table usuario_academia
    owner to my_gym;

create index usuario_academia_academia_2b28677c
    on usuario_academia (academia);

create index usuario_academia_usuario_eb9ee674
    on usuario_academia (usuario);


        
        """