# Generated by Django 5.1.2 on 2025-06-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_gym', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='aluno',
        ),
    ]
