# Generated by Django 5.1.2 on 2025-05-25 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_gym', '0002_session_questions_delete_chats'),
        ('usuario', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('user', 'session_id')},
        ),
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
    ]
