# Generated by Django 5.1.2 on 2025-04-08 17:13

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0005_usuarioacademia_data_contratacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('SUPLEMENTO', 'suplemento'), ('Acessorio', 'acessorio'), ('ROUPA', 'roupa'), ('BEBIDA', 'bebida'), ('ALIMENTO', 'alimento'), ('OUTROS', 'outros')], default='outros', max_length=100)),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.academia')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LoteProduto',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_validade', models.DateField()),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lote_produto', to='produto.produto')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
