# Generated by Django 5.1.2 on 2025-06-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteproduto',
            name='data_validade',
        ),
    ]
