# Generated by Django 5.1.2 on 2025-06-13 02:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_exercice_academia'),
        ('produto', '0002_remove_loteproduto_data_validade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProduto',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True)),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created', editable=False, null=True)),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified', editable=False, null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.URLField(blank=True, null=True, verbose_name='foto')),
                ('data_cadastro', models.DateField(blank=True, editable=False)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
                ('estoque_minimo', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(choices=[('SUPLEMENTO', 'suplemento'), ('Acessorio', 'acessorio'), ('ROUPA', 'roupa'), ('BEBIDA', 'bebida'), ('ALIMENTO', 'alimento'), ('OUTROS', 'outros')], default='outros', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('academia', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academia.academia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical produto',
                'verbose_name_plural': 'historical produtos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
