# Generated by Django 5.1.2 on 2025-06-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_historicalproduto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalProduto',
        ),
    ]
