# Generated by Django 5.1.2 on 2025-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_marca_alter_produto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduto',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loteproduto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
    ]
