# Generated by Django 5.1.2 on 2025-05-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_loteproduto_preco_total_loteproduto_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
