# Generated by Django 5.1.2 on 2025-06-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_delete_historicalproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('SUPLEMENTO', 'suplemento'), ('ACESSORIO', 'acessorio'), ('ROUPA', 'roupa'), ('BEBIDA', 'bebida'), ('ALIMENTO', 'alimento'), ('OUTROS', 'outros'), ('EQUIPAMENTO', 'equipamento')], default='outros', max_length=100),
        ),
    ]
