# Generated by Django 5.1.2 on 2025-05-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_estoque_minimo_produto_quantidade_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loteproduto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.AlterModelTable(
            name='loteproduto',
            table='lote_produto',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
